spring.mail.username=katlegomakoti@gmail.com
spring.mail.password=bale nbto cfmq jrcy # Brevo
brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${BREVO_FROM_EMAIL}
brevo.from.name=${BREVO_FROM_NAME}
brevo.notification.to=${BREVO_NOTIFICATION_TO}